### PR TITLE
Project management

### PR DESCRIPTION
**Pull request by LukeHankey**
Cleaned up the project a little bit.

Includes autoflakes and pyright as new pre-commit hooks. If you haven't done so yet, just run `pre-commit install` in your terminal within your virtual environment. Have upgraded the tools to their latest versions.

Changes made to the existing code based on the hooks.

Using the default package manager (pip) so we don't need the Pipfile or the dev-requirements.txt.

License file adjusted to include the team name.

### CODE REVIEW

**Comment by busterbeam** [comment]
`regular` should have argument `filename` as type `str`

**Comment by busterbeam** [comment]
> `regular` should have argument `filename` as type `str`

wait!?! yea just drop `if __name__` in`common`

**Comment by busterbeam** [comment]
I did message @EarthKiii about using 3.10 for pyright. There are no rules saying what version of python to use. 3.11 is still in bugs phase while 3.10 is in security improvements

**Comment by busterbeam** [comment]
Futhermore why is black going under tool.isort?

**Comment by LukeHankey** [comment]
> I did message @EarthKiii about using 3.10 for pyright. There are no rules saying what version of python to use. 3.11 is still in bugs phase while 3.10 is in security improvements

Ah, I thought 3.11 was the preference since that is what was used for the qualifier. If we are all using 3.10, I'll switch this on here then 👍

**Comment by LukeHankey** [comment]
> Futhermore why is black going under tool.isort?

isort and black don't play nice together with certain import styling so the **profile** for isort is set to black.

**Comment by busterbeam** [comment]
> > I did message @EarthKiii about using 3.10 for pyright. There are no rules saying what version of python to use. 3.11 is still in bugs phase while 3.10 is in security improvements
> 
> Ah, I thought 3.11 was the preference since that is what was used for the qualifier. If we are all using 3.10, I'll switch this on here then 👍 

That's just one person I would prefer 3.11. If the qualifier was in that, that is an indicator so 3.11

**Review by busterbeam — APPROVED** [review]

**Pull request merged**
